'use client';

import { Star, MapPin, CheckCircle, Eye, Heart, Phone } from 'lucide-react';
import Image from 'next/image';
import Link from 'next/link';

// Profile types with their colors
const profileTypes = {
  solo: { color: 'bg-purple-500' },
  privat: { color: 'bg-indigo-500' },
  salon: { color: 'bg-teal-500' },
  escort_agency: { color: 'bg-pink-500' },
  digital_agency: { color: 'bg-blue-500', label: 'Digitální Agentura' },
  swingers_club: { color: 'bg-red-500', label: 'Swingers klub' },
  night_club: { color: 'bg-orange-500', label: 'Night Club' },
  strip_club: { color: 'bg-yellow-500', label: 'Strip Club' },
};

export const profiles = [
  {
    id: 1,
    name: 'Lucie',
    age: 24,
    location: 'Praha 1',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 127,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 2,
    name: 'Anastasia',
    age: 26,
    location: 'Brno',
    category: 'Erotické masérky',
    rating: 5.0,
    reviews: 89,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Paradise Massage',
    phone: '+420 606 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 3,
    name: 'Nikola',
    age: 23,
    location: 'Praha 2',
    category: 'Domina',
    rating: 4.8,
    reviews: 156,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 723 345 678',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 4,
    name: 'Isabella',
    age: 25,
    location: 'Ostrava',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 92,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Luxury Private',
    phone: '+420 608 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 5,
    name: 'Michaela',
    age: 27,
    location: 'Plzeň',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 64,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Tantra Salon',
    phone: '+420 777 567 890',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 6,
    name: 'Karolína',
    age: 22,
    location: 'Liberec',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 78,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elite Escorts',
    phone: '+420 603 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 7,
    name: 'Tereza',
    age: 29,
    location: 'Olomouc',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 95,
    verified: false,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Privát Venus',
    phone: '+420 721 789 012',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 8,
    name: 'Petra',
    age: 25,
    location: 'Praha 5',
    category: 'Digitální',
    rating: 5.0,
    reviews: 112,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'OnlyFans Agency',
    phone: '+420 777 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 9,
    name: 'Veronika',
    age: 28,
    location: 'Brno',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 143,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 606 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 10,
    name: 'Simona',
    age: 24,
    location: 'Praha 3',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 87,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 723 012 345',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 11,
    name: 'Zuzana',
    age: 26,
    location: 'Ostrava',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 56,
    verified: false,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Dark Paradise',
    phone: '+420 608 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 12,
    name: 'Daniela',
    age: 30,
    location: 'České Budějovice',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 102,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Exclusive',
    phone: '+420 777 234 567',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 13,
    name: 'Natálie',
    age: 23,
    location: 'Karlovy Vary',
    category: 'Erotické masérky',
    rating: 5.0,
    reviews: 134,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'VIP Models',
    phone: '+420 603 345 678',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 14,
    name: 'Andrea',
    age: 27,
    location: 'Hradec Králové',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 91,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Relax Centrum',
    phone: '+420 721 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 15,
    name: 'Markéta',
    age: 25,
    location: 'Pardubice',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 73,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Studio M',
    phone: '+420 606 567 890',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 16,
    name: 'Lenka',
    age: 29,
    location: 'Zlín',
    category: 'Domina',
    rating: 4.9,
    reviews: 108,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 17,
    name: 'Barbora',
    age: 26,
    location: 'Praha 4',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 83,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 18,
    name: 'Kristýna',
    age: 24,
    location: 'Ústí nad Labem',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 67,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Wellness Spa',
    phone: '+420 721 890 123',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 19,
    name: 'Monika',
    age: 28,
    location: 'Jihlava',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 94,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Sweet Dreams',
    phone: '+420 777 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 20,
    name: 'Kateřina',
    age: 23,
    location: 'Teplice',
    category: 'Erotické masérky',
    rating: 4.6,
    reviews: 52,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 012 345',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 21,
    name: 'Adéla',
    age: 27,
    location: 'Děčín',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 79,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Diamond Girls',
    phone: '+420 606 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 22,
    name: 'Ivana',
    age: 25,
    location: 'Havířov',
    category: 'Domina',
    rating: 4.7,
    reviews: 61,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 723 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 23,
    name: 'Denisa',
    age: 29,
    location: 'Frýdek-Místek',
    category: 'Holky na sex',
    rating: 5.0,
    reviews: 118,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Club Paradise',
    phone: '+420 608 345 678',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 24,
    name: 'Klára',
    age: 26,
    location: 'Mladá Boleslav',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 86,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Erotic Touch',
    phone: '+420 777 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 25,
    name: 'Pavlína',
    age: 24,
    location: 'Praha 6',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 98,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 26,
    name: 'Nikol',
    age: 22,
    location: 'Brno',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 72,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Dream Spa',
    phone: '+420 721 678 901',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 27,
    name: 'Gabriela',
    age: 28,
    location: 'Opava',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 84,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Golden Touch',
    phone: '+420 777 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 28,
    name: 'Sabina',
    age: 25,
    location: 'Kladno',
    category: 'Domina',
    rating: 4.9,
    reviews: 103,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 29,
    name: 'Eliška',
    age: 23,
    location: 'Most',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 58,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Premium Girls',
    phone: '+420 606 901 234',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 30,
    name: 'Růžena',
    age: 27,
    location: 'Karviná',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 91,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Sensual Massage',
    phone: '+420 723 012 345',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 31,
    name: 'Johana',
    age: 26,
    location: 'Chomutov',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 76,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Secret Place',
    phone: '+420 608 123 456',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 32,
    name: 'Štěpánka',
    age: 24,
    location: 'Tábor',
    category: 'Digitální',
    rating: 5.0,
    reviews: 145,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Digital Stars',
    phone: '+420 777 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 33,
    name: 'Vendula',
    age: 29,
    location: 'Praha 7',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 117,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 345 678',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 34,
    name: 'Renata',
    age: 25,
    location: 'Prostějov',
    category: 'Erotické masérky',
    rating: 4.6,
    reviews: 63,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 721 456 789',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 35,
    name: 'Alena',
    age: 30,
    location: 'Přerov',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 88,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Luxury Club',
    phone: '+420 608 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 36,
    name: 'Jaroslava',
    age: 26,
    location: 'Kroměříž',
    category: 'Domina',
    rating: 4.7,
    reviews: 71,
    verified: false,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 678 901',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 37,
    name: 'Kamila',
    age: 23,
    location: 'Třinec',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 96,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Angels Escort',
    phone: '+420 603 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 38,
    name: 'Miroslava',
    age: 28,
    location: 'Třebíč',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 82,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Touch of Heaven',
    phone: '+420 606 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 39,
    name: 'Radka',
    age: 27,
    location: 'Cheb',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 69,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Red Velvet',
    phone: '+420 723 901 234',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 40,
    name: 'Jitka',
    age: 24,
    location: 'Praha 8',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 104,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 012 345',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 41,
    name: 'Hana',
    age: 25,
    location: 'Kolín',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 54,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 123 456',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 42,
    name: 'Jana',
    age: 29,
    location: 'Litoměřice',
    category: 'Digitální',
    rating: 4.8,
    reviews: 93,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'OnlyAngels',
    phone: '+420 603 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 43,
    name: 'Michaela',
    age: 26,
    location: 'Písek',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 77,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Private Dreams',
    phone: '+420 721 345 678',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 44,
    name: 'Blanka',
    age: 23,
    location: 'Trutnov',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 81,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Spa Desire',
    phone: '+420 608 456 789',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 45,
    name: 'Iveta',
    age: 27,
    location: 'Šumperk',
    category: 'Domina',
    rating: 4.9,
    reviews: 99,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 46,
    name: 'Luisa',
    age: 24,
    location: 'Uherské Hradiště',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 68,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Luxury Angels',
    phone: '+420 603 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 47,
    name: 'Silvie',
    age: 28,
    location: 'Praha 9',
    category: 'Holky na sex',
    rating: 5.0,
    reviews: 132,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 606 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 48,
    name: 'Eva',
    age: 25,
    location: 'Kutná Hora',
    category: 'Erotické masérky',
    rating: 4.6,
    reviews: 59,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Harmony Spa',
    phone: '+420 723 890 123',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 49,
    name: 'Dagmar',
    age: 30,
    location: 'Znojmo',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 87,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Pink Palace',
    phone: '+420 608 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 50,
    name: 'Martina',
    age: 26,
    location: 'Strakonice',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 73,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 012 345',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 51,
    name: 'Olga',
    age: 27,
    location: 'Jičín',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 101,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Royal Massage',
    phone: '+420 603 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 52,
    name: 'Ludmila',
    age: 29,
    location: 'Nový Jičín',
    category: 'Domina',
    rating: 4.8,
    reviews: 85,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 721 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 53,
    name: 'Božena',
    age: 24,
    location: 'Klatovy',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 62,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Velvet Lounge',
    phone: '+420 608 345 678',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 54,
    name: 'Naďa',
    age: 23,
    location: 'Benešov',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 70,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elite Models',
    phone: '+420 777 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 55,
    name: 'Soňa',
    age: 28,
    location: 'Praha 10',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 108,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 56,
    name: 'Vlaďka',
    age: 25,
    location: 'Rychnov nad Kněžnou',
    category: 'Digitální',
    rating: 4.8,
    reviews: 96,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Fansly CZ',
    phone: '+420 606 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 57,
    name: 'Zdena',
    age: 26,
    location: 'Mělník',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 75,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Eden Massage',
    phone: '+420 723 789 012',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 58,
    name: 'Doubravka',
    age: 27,
    location: 'Vsetín',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 89,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Exclusive Privat',
    phone: '+420 608 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 59,
    name: 'Bronislava',
    age: 24,
    location: 'Beroun',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 57,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 901 234',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 60,
    name: 'Milena',
    age: 29,
    location: 'Náchod',
    category: 'Domina',
    rating: 4.9,
    reviews: 106,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 012 345',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 61,
    name: 'Lenka',
    age: 23,
    location: 'Blansko',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 66,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'VIP Prague',
    phone: '+420 721 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 62,
    name: 'Marcela',
    age: 28,
    location: 'Rakovník',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 92,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Bliss Spa',
    phone: '+420 608 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 63,
    name: 'Helena',
    age: 25,
    location: 'Hodonín',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 79,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Sweet Touch',
    phone: '+420 777 345 678',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 64,
    name: 'Květa',
    age: 26,
    location: 'Příbram',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 113,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 65,
    name: 'Irena',
    age: 27,
    location: 'Litvínov',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 61,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 606 567 890',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 66,
    name: 'Drahomíra',
    age: 30,
    location: 'Jindřichův Hradec',
    category: 'Digitální',
    rating: 4.8,
    reviews: 88,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Content Queens',
    phone: '+420 723 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 67,
    name: 'Vlasta',
    age: 24,
    location: 'Kopřivnice',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 74,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Fantasy Studio',
    phone: '+420 608 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 68,
    name: 'Libuše',
    age: 28,
    location: 'Česká Lípa',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 105,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Angel Touch',
    phone: '+420 777 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 69,
    name: 'Zdeňka',
    age: 25,
    location: 'Havlíčkův Brod',
    category: 'Domina',
    rating: 4.8,
    reviews: 83,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 901 234',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 70,
    name: 'Svatava',
    age: 23,
    location: 'Valašské Meziříčí',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 56,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Secret Escort',
    phone: '+420 721 012 345',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 71,
    name: 'Bohumila',
    age: 29,
    location: 'Krnov',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 71,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Nirvana Spa',
    phone: '+420 608 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 72,
    name: 'Anežka',
    age: 26,
    location: 'Prachatice',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 90,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Passion Club',
    phone: '+420 777 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 73,
    name: 'Berta',
    age: 24,
    location: 'Rokycany',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 67,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 603 345 678',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 74,
    name: 'Cecílie',
    age: 27,
    location: 'Sokolov',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 98,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Lotus Massage',
    phone: '+420 606 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 75,
    name: 'Dana',
    age: 28,
    location: 'Nymburk',
    category: 'Digitální',
    rating: 5.0,
    reviews: 128,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Stars Only',
    phone: '+420 723 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 76,
    name: 'Erika',
    age: 25,
    location: 'Dvůr Králové',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 64,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Royal Privat',
    phone: '+420 608 678 901',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 77,
    name: 'Františka',
    age: 23,
    location: 'Kadaň',
    category: 'Domina',
    rating: 4.8,
    reviews: 86,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 78,
    name: 'Gita',
    age: 26,
    location: 'Šternberk',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 78,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elegant Escort',
    phone: '+420 603 890 123',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 79,
    name: 'Hermína',
    age: 29,
    location: 'Rožnov pod Radhoštěm',
    category: 'Erotické masérky',
    rating: 4.9,
    reviews: 111,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Tantra Temple',
    phone: '+420 721 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 80,
    name: 'Ivana',
    age: 24,
    location: 'Kralupy nad Vltavou',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 59,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 012 345',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 81,
    name: 'Jaromíra',
    age: 27,
    location: 'Louny',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 93,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Diamond Privat',
    phone: '+420 777 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 82,
    name: 'Kamila',
    age: 25,
    location: 'Bruntál',
    category: 'Erotické masérky',
    rating: 4.7,
    reviews: 72,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Serenity Spa',
    phone: '+420 603 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 83,
    name: 'Květoslava',
    age: 28,
    location: 'Pacov',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 107,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 606 345 678',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 84,
    name: 'Laura',
    age: 23,
    location: 'Bílina',
    category: 'Digitální',
    rating: 4.8,
    reviews: 91,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'CZ Creators',
    phone: '+420 723 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 85,
    name: 'Magda',
    age: 26,
    location: 'Aš',
    category: 'Domina',
    rating: 4.7,
    reviews: 69,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 567 890',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 86,
    name: 'Nina',
    age: 24,
    location: 'Čáslav',
    category: 'Holky na sex',
    rating: 4.6,
    reviews: 55,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Top Girls',
    phone: '+420 777 678 901',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 87,
    name: 'Olga',
    age: 29,
    location: 'Tachov',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 89,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Venus Massage',
    phone: '+420 603 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 88,
    name: 'Petra',
    age: 27,
    location: 'Domažlice',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 76,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Passion Privat',
    phone: '+420 721 890 123',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 89,
    name: 'Regina',
    age: 25,
    location: 'Říčany',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 102,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 608 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 90,
    name: 'Sabina',
    age: 26,
    location: 'Vyškov',
    category: 'Erotické masérky',
    rating: 4.6,
    reviews: 63,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 012 345',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 91,
    name: 'Taťána',
    age: 28,
    location: 'Litvínov',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 95,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Velvet Touch',
    phone: '+420 603 123 456',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 92,
    name: 'Úrsula',
    age: 23,
    location: 'Milevsko',
    category: 'Domina',
    rating: 4.7,
    reviews: 68,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 606 234 567',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 93,
    name: 'Vendula',
    age: 24,
    location: 'Mikulov',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 109,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Prestige Escort',
    phone: '+420 723 345 678',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 94,
    name: 'Wilhelmína',
    age: 27,
    location: 'Cvikov',
    category: 'Erotické masérky',
    rating: 4.8,
    reviews: 84,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Passion Spa',
    phone: '+420 608 456 789',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 95,
    name: 'Xenie',
    age: 29,
    location: 'Lanškroun',
    category: 'Digitální',
    rating: 4.9,
    reviews: 116,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Premium Content',
    phone: '+420 777 567 890',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 96,
    name: 'Yveta',
    age: 25,
    location: 'Sezemice',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 77,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Private Heaven',
    phone: '+420 603 678 901',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 97,
    name: 'Zora',
    age: 26,
    location: 'Poděbrady',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 92,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 721 789 012',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 98,
    name: 'Blažena',
    age: 24,
    location: 'Votice',
    category: 'Erotické masérky',
    rating: 4.6,
    reviews: 60,
    verified: false,
    isNew: true,
    isPopular: false,
    profileType: 'salon' as keyof typeof profileTypes,
    businessName: 'Relaxation Zone',
    phone: '+420 608 890 123',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 99,
    name: 'Čestmíra',
    age: 28,
    location: 'Sedlčany',
    category: 'Domina',
    rating: 4.9,
    reviews: 100,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'solo' as keyof typeof profileTypes,
    businessName: null,
    phone: '+420 777 901 234',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 100,
    name: 'Daniela',
    age: 27,
    location: 'Blatná',
    category: 'Holky na sex',
    rating: 5.0,
    reviews: 139,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Royal Escort',
    phone: '+420 603 012 345',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  // Privát profily
  {
    id: 101,
    name: 'Simona',
    age: 25,
    location: 'Praha 5',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 95,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Pink Palace',
    phone: '+420 777 555 111',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 102,
    name: 'Kateřina',
    age: 28,
    location: 'Brno',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 112,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Pink Palace',
    phone: '+420 777 555 111',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 103,
    name: 'Alena',
    age: 24,
    location: 'Ostrava',
    category: 'Holky na sex',
    rating: 4.7,
    reviews: 78,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Velvet Club',
    phone: '+420 606 444 222',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 104,
    name: 'Monika',
    age: 26,
    location: 'Ostrava',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 89,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'privat' as keyof typeof profileTypes,
    businessName: 'Velvet Club',
    phone: '+420 606 444 222',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  // Escort Agentura profily
  {
    id: 105,
    name: 'Tereza',
    age: 23,
    location: 'Praha 1',
    category: 'Holky na sex',
    rating: 5.0,
    reviews: 145,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elite Prague Escorts',
    phone: '+420 777 888 999',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 106,
    name: 'Veronika',
    age: 25,
    location: 'Praha 1',
    category: 'Holky na sex',
    rating: 4.9,
    reviews: 134,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elite Prague Escorts',
    phone: '+420 777 888 999',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 107,
    name: 'Nikola',
    age: 27,
    location: 'Praha 1',
    category: 'Holky na sex',
    rating: 4.8,
    reviews: 98,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'escort_agency' as keyof typeof profileTypes,
    businessName: 'Elite Prague Escorts',
    phone: '+420 777 888 999',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  // Digitální agentura profily
  {
    id: 108,
    name: 'Adéla',
    age: 22,
    location: 'Praha 2',
    category: 'Digitální',
    rating: 4.9,
    reviews: 156,
    verified: true,
    isNew: true,
    isPopular: true,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'OnlyFans CZ',
    phone: '+420 603 777 888',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 109,
    name: 'Karolína',
    age: 24,
    location: 'Praha 2',
    category: 'Digitální',
    rating: 5.0,
    reviews: 189,
    verified: true,
    isNew: false,
    isPopular: true,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'OnlyFans CZ',
    phone: '+420 603 777 888',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 110,
    name: 'Barbora',
    age: 23,
    location: 'Brno',
    category: 'Digitální',
    rating: 4.8,
    reviews: 123,
    verified: true,
    isNew: false,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Czech Creators',
    phone: '+420 777 999 111',
    isOnline: true,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
  {
    id: 111,
    name: 'Klára',
    age: 25,
    location: 'Brno',
    category: 'Digitální',
    rating: 4.7,
    reviews: 98,
    verified: true,
    isNew: true,
    isPopular: false,
    profileType: 'digital_agency' as keyof typeof profileTypes,
    businessName: 'Czech Creators',
    phone: '+420 777 999 111',
    isOnline: false,
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=400&h=500&fit=crop',
  },
];

export default function TopProfiles() {
  return (
    <section className="py-20 relative">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold mb-4">
            <span className="gradient-text">Prohlédněte si erotické profily</span>
          </h2>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Ověřené erotické profily ze všech kategorií
          </p>
        </div>

        {/* Profiles Grid */}
        <div className="grid grid-cols-5 gap-4">
          {profiles.slice(0, 15).map((profile) => (
            <Link
              key={profile.id}
              href={`/profil/${profile.id}`}
              className="glass rounded-2xl overflow-hidden card-hover group"
            >
              {/* Image Container */}
              <div className="relative h-64 overflow-hidden bg-dark-800">
                {/* Placeholder with gradient */}
                <div className="absolute inset-0 bg-gradient-to-br from-primary-500/20 to-purple-500/20"></div>

                {/* Badges */}
                <div className="absolute top-2 left-2 flex flex-col gap-1 z-10">
                  {profile.isNew && (
                    <span className="bg-blue-500 px-1.5 py-0.5 rounded text-[10px] font-semibold">
                      Nový
                    </span>
                  )}
                  {profile.isPopular && (
                    <span className="bg-orange-500 px-1.5 py-0.5 rounded text-[10px] font-semibold flex items-center space-x-0.5">
                      <span className="text-[9px]">🔥</span>
                      <span>Populární</span>
                    </span>
                  )}
                </div>

                {/* Favorite Button */}
                <button className="absolute top-2 right-2 z-10 bg-black/50 w-8 h-8 rounded-full flex items-center justify-center hover:bg-black/70 transition-colors">
                  <Heart className="w-4 h-4 text-white" />
                </button>

                {/* Hover Overlay */}
                <div className="absolute inset-0 bg-gradient-to-t from-dark-950 via-dark-950/50 to-transparent opacity-60 group-hover:opacity-80 transition-opacity"></div>
              </div>

              {/* Content */}
              <div className="p-3">
                {/* Profile Type Badge - Large */}
                <div className="mb-2">
                  <span className={`${profileTypes[profile.profileType].color} px-2 py-1 rounded-md text-xs font-bold inline-block truncate max-w-full`}>
                    {profile.profileType === 'solo'
                      ? 'SOLO'
                      : profile.profileType === 'salon'
                      ? `Salon ${profile.businessName}`
                      : profile.profileType === 'privat'
                      ? `Privát ${profile.businessName}`
                      : profile.profileType === 'escort_agency'
                      ? profile.businessName
                      : profile.businessName
                    }
                  </span>
                </div>

                <h3 className="text-base font-semibold mb-1 truncate flex items-center gap-1">
                  {profile.verified && (
                    <CheckCircle className="w-4 h-4 text-green-500 flex-shrink-0" />
                  )}
                  <span>{profile.name}, {profile.age}</span>
                  {/* Online Status */}
                  <span className={`w-2 h-2 rounded-full flex-shrink-0 ${profile.isOnline ? 'bg-green-500' : 'bg-gray-500'}`}></span>
                </h3>

                <div className="flex items-center space-x-1 text-xs text-gray-400 mb-1">
                  <MapPin className="w-3 h-3" />
                  <span className="truncate">{profile.location}</span>
                </div>

                <div className="flex items-center space-x-1 text-xs text-gray-400 mb-2">
                  <Phone className="w-3 h-3" />
                  <span className="truncate">{profile.phone}</span>
                </div>

                <div className="flex items-center justify-between text-xs">
                  <span className="text-gray-500 truncate">{profile.category}</span>
                  <div className="flex items-center space-x-1">
                    <Star className="w-3 h-3 text-yellow-400" fill="currentColor" />
                    <span className="font-medium">{profile.rating}</span>
                  </div>
                </div>
              </div>
            </Link>
          ))}
        </div>

        {/* View All Button */}
        <div className="text-center mt-12">
          <Link
            href="/profily"
            className="inline-flex items-center space-x-2 gradient-primary px-8 py-4 rounded-xl font-medium hover:shadow-lg hover:shadow-primary-500/50 transition-all"
          >
            <span>Zobrazit všechny erotické profily</span>
            <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17 8l4 4m0 0l-4 4m4-4H3" />
            </svg>
          </Link>
        </div>
      </div>
    </section>
  );
}
